siteTitle="Shoebox"
baseColor = "#FF3D2E"
linkPrefix = "/shoebox"
topicPages = [
  "/topics/",
  "/topics/angularjs/",
  "/topics/Bootstrap/",
  "/topics/code-practice/",
  "/topics/compilers/",
  "/topics/css/",
  "/topics/d3js/",
  "/topics/data-visualization/",
  "/topics/git/",
  "/topics/GraphQL/",
  "/topics/heroku/",
  "/topics/hosting/",
  "/topics/html-css/",
  "/topics/image-editing/",
  "/topics/image-storage/",
  "/topics/interviews/",
  "/topics/javascript/",
  "/topics/laravel/",
  "/topics/mean/",
  "/topics/miscellaneous/",
  "/topics/MobX/",
  "/topics/module-building/",
  "/topics/mongodb/",
  "/topics/network-programming/",
  "/topics/nix/",
  "/topics/node/",
  "/topics/performance/",
  "/topics/programming-for-kids/",
  "/topics/react/",
  "/topics/redux/",
  "/topics/style-guide/",
  "/topics/task-runner/",
  "/topics/testing/",
  "/topics/ui-ux/",
  "/topics/vuejs/",
]
