siteTitle="Shoebox"
baseColor = "#FF3D2E"
linkPrefix = "/shoebox"
docPages = [
  "/docs/",
  "/docs/angularjs/",
  "/docs/Bootstrap/",
  "/docs/code-practice/",
  "/docs/compilers/",
  "/docs/css/",
  "/docs/d3js/",
  "/docs/data-visualization/",
  "/docs/git/",
  "/docs/GraphQL/",
  "/docs/heroku/",
  "/docs/hosting/",
  "/docs/html-css/",
  "/docs/image-editing/",
  "/docs/image-storage/",
  "/docs/interviews/",
  "/docs/javascript/",
  "/docs/laravel/",
  "/docs/mean/",
  "/docs/miscellaneous/",
  "/docs/MobX/",
  "/docs/module-building/",
  "/docs/mongodb/",
  "/docs/network-programming/",
  "/docs/nix/",
  "/docs/node/",
  "/docs/performance/",
  "/docs/programming-for-kids/",
  "/docs/react/",
  "/docs/redux/",
  "/docs/style-guide/",
  "/docs/task-runner/",
  "/docs/testing/",
  "/docs/ui-ux/",
  "/docs/vuejs/",

  

  

]
